Portal/Portal/Models/Nyu/nyuinvoicedetailexportmodal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portal.UI.Models.Nyu
{
    public class nyuinvoicedetailexportmodal
    {

        public string ReferenceNo { get; set; }
        public string RequestorId { get; set; }
        public string InvoiceDate { get; set; }
        public string InvoiceNo { get; set; }
        public string NAME { get; set; }
        public string AUTHORISEDBY { get; set; }
        public string TRAVELCODE { get; set; }
        public string AirTicket { get; set; }
        public string Hotel { get; set; }
        public string GroundTransport { get; set; }
        public string OtherServices { get; set; }
        public string VAT { get; set; }
        public string Exceptio { get; set; }
        public string Total { get; set; }
        public string Fund { get; set; }
        public string Account { get; set; }
        public string ORG { get; set; }
        public string Project { get; set; }
        public string Progra { get; set; }
        public string TravelDate { get; set; }
        public string ReturnDate { get; set; }
        public string OriginCity { get; set; }
        public string SEC2 { get; set; }
        public string SEC3 { get; set; }
        public string SEC4 { get; set; }
        public string SEC5 { get; set; }
        public string SEC6 { get; set; }
        public string FinalCity { get; set; }
        public string CHECK_IN { get; set; }
        public string CHECK_OUT { get; set; }
    }
}

Portal/Portal/Models/Nyu/nyuinvoicedetailmodal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portal.UI.Models.Nyu
{
    public class nyuinvoicedetailmodal
    {
        public long id { get;set; }
        public string servicetype { get; set; }
        public string bookno { get; set; }
        public string pax { get; set; }
        public string fromdate { get; set; }
        public string todate { get; set; }
        public string provider { get; set; }
        public string route { get; set; }
        public string fare { get; set; }
        public string tax { get; set; }
        public string vat { get; set; }
        public string total { get; set; }
        public string authcode { get; set; }
        public string account { get; set; }
        public string fund { get; set; }
        public string org { get; set; }
        public string project { get; set; }
        public string program { get; set; }
        public int status { get; set; }
        public string serviceFee { get; set; }


        public long invoiceid { get; set; }
    }
}

Portal/Portal/Models/Nyu/nyuinvoicemodal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portal.UI.Models.Nyu
{
    public class nyuinvoicemodal
    {
        public Int64 id { get; set; }
        public string lpono { get; set; }
        public string invoiceno { get; set; }
        public string invoicedate { get; set; }
        public string verifiedby { get; set; }
        public string verifiedon { get; set; }
        public int paystatus { get; set; }
        public string travelcode { get; set; }
        public string authcode { get; set; }
        public int status { get; set; } 
        public string company { get; set; }
        public List<nyuinvoicedetailmodal> nyuinvoicedetailmodal { get; set; }
        public bool IsAttached { get; set; }
    }
}

Portal/Portal/Models/Nyu/nyusoamodal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portal.UI.Models.Nyu
{
    public class nyusoamodal
    {
        public Int64 id { get; set; }
        public string lpono { get; set; }
        public string invoiceno { get; set; }
        public string invoicedate { get; set; }
        public string debit { get; set; }
        public string credit { get; set; }
        public string balance { get; set; }

        public Int64 invoiceid { get; set; }
        public bool IsAttached { get; set; }
    }
}

Portal/Portal/Controllers/NyuController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging.Abstractions;
using Nirvana_Portal.Data.Nyu;
using Portal.Data;
using Portal.Service.Interface;
using Portal.UI.Models.Nyu;

namespace Portal.UI.Controllers
{
    [Authorize(Roles = "NyuUser,NyuNtt")]
    public class NyuController : Controller
    {
        public INyuService _INyuService;
        public IAttachmentService _IAttachmentService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        public static string nyuFileLocation = @"D:\Attachments\";
        public static string infordocslocation = @"D:\InforDocs\";
        public NyuController(INyuService nyuService, IAttachmentService attachmentService, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _INyuService = nyuService;
            _IAttachmentService = attachmentService;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        [HttpGet]
        public IActionResult StaffveriLoad()
        {
            return View("../Nyu/View_StaffveriLoad");
        }
        [HttpGet]
        public IActionResult OpenInvoicesLoad()
        {
            return View("../Nyu/View_OpenInvoicesLoad");
        }
        [HttpGet]
        public IActionResult SoaLoad()
        {
            return View("../Nyu/View_SoaLoad");
        }
        [HttpGet]
        public IActionResult ArchievesInvoicesLoad()
        {
            return View("../Nyu/View_ArchievesInvoicesLoad");
        }

        [HttpGet]
        public ActionResult GetStaffveriLoad(string serlpono = "", string serinvoiceno = "", string serinvfromdate = "", string serinvtodate = "", long serinvstatus = 0, int page = 1)
        {
            try
            {
                serlpono = serlpono ?? "";
                serinvoiceno = serinvoiceno ?? "";
                DateTime From = string.IsNullOrEmpty(serinvfromdate) ? DateTime.MinValue : DateTime.ParseExact(serinvfromdate, "dd/MM/yyyy", null);
                DateTime To = string.IsNullOrEmpty(serinvtodate) ? DateTime.MaxValue : DateTime.ParseExact(serinvtodate, "dd/MM/yyyy", null);
                int pageIndex = Convert.ToInt32(1) - 1;
                var Data = _INyuService.GetStaffverificationload().OrderByDescending(x => x.createddate).Where(x =>
              (x.lpono.ToLower().Contains(serlpono.ToLower()) || serlpono == "")
               && (x.invoicedate >= From && x.invoicedate <= To)
              && (x.invoiceno.ToLower().Contains(serinvoiceno.ToLower()) || serinvoiceno == "")
              && (x.status == serinvstatus || serinvstatus == 0)
            ).Select(x => new nyuinvoicemodal
            {
                id = x.id,
                lpono = x.lpono==null?"":x.lpono.ToString(),
                invoiceno = x.invoiceno==null?"": x.invoiceno.ToString(),
                invoicedate = x.invoicedate==null?"": x.invoicedate.Value.ToString("dd-MMM-yyyy"),
                travelcode= x.travelcode==null?"":x.travelcode.ToString(),
                authcode=x.authcode==null?"":x.authcode.ToString(),
                status = x.status
            }); ;

                var datalist = Data.Skip((page - 1) * 250).Take(250).ToList();
                foreach (var item in datalist)
                {
                    var details = _INyuService.GetInvoiceDetail(item.id).Select(x => new nyuinvoicedetailmodal
                    {
                        servicetype = x.servicetype == null ? "" : x.servicetype.ToString(),
                        bookno = x.bookno == null ? "" : x.bookno.ToString(),
                        pax = x.pax == null ? "" : x.pax.ToString(),
                        fromdate = x.fromdate == null ? "" : x.fromdate.Value.ToString("dd-MMM-yyyy"),
                        todate = x.todate == null ? "" : x.todate.Value.ToString("dd-MMM-yyyy"),
                        provider = x.provider == null ? "" : x.provider.ToString(),
                        route = x.route == null ? "" : x.route.ToString(),
                        fare = x.fare.ToString("N2"),
                        tax = x.tax.ToString("N2"),
                        vat = x.vat.ToString("N2"),
                        total = x.total.ToString("N2"),
                        authcode = x.authcode == null ? "" : x.authcode.ToString(),
                        account = x.account == null ? "" : x.account.ToString(),
                        fund = x.fund == null ? "" : x.fund.ToString(),
                        org = x.org == null ? "" : x.org.ToString(),
                        project = x.project == null ? "" : x.project.ToString(),
                        program = x.program == null ? "" : x.program.ToString()
                    }).ToList(); ;

                    item.nyuinvoicedetailmodal = details;
                }


                var Results = new
                {
                    //Data = Data.Skip((page - 1) * 250).Take(250).ToList(),
                    Data = datalist,
                    page,
                    Total = Data.Count()
                };
                return Json(Results);
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        [HttpGet]
        public ActionResult GetOpenInvoicesLoad(string serlpono = "", string serinvoiceno = "", string serinvfromdate = "", string serinvtodate = "", int page = 1)
        {
            try
            {
                serlpono = serlpono ?? "";
                serinvoiceno = serinvoiceno ?? "";
                DateTime From = string.IsNullOrEmpty(serinvfromdate) ? DateTime.MinValue : DateTime.ParseExact(serinvfromdate, "dd/MM/yyyy", null);
                DateTime To = string.IsNullOrEmpty(serinvtodate) ? DateTime.MaxValue : DateTime.ParseExact(serinvtodate, "dd/MM/yyyy", null);
                int pageIndex = Convert.ToInt32(1) - 1;
                var Data = _INyuService.GetCustomerInvoicesLoad().OrderByDescending(x => x.createddate).Where(x =>
              (x.lpono.ToLower().Contains(serlpono.ToLower()) || serlpono == "")
               && (x.invoicedate >= From && x.invoicedate <= To)
              && (x.invoiceno.ToLower().Contains(serinvoiceno.ToLower()) || serinvoiceno == "")
               && (x.paystatus == 1)
            ).Select(x => new nyuinvoicemodal
            {
                id = x.id,
                lpono = x.lpono == null ? "" : x.lpono.ToString(),
                invoiceno = x.invoiceno == null ? "" : x.invoiceno.ToString(),
                invoicedate = x.invoicedate == null ? "" : x.invoicedate.Value.ToString("dd-MMM-yyyy"),
                verifiedby = x.verifieduser.fullname,
                verifiedon = x.verifiedon.Value.ToString("dd-MMM-yyyy"),
            });

                var list = Data.Skip((page - 1) * 250).Take(250).ToList();

                foreach (var item in list)
                {
                    if (item.invoiceno != null)
                    {
                       
                            string csvPath = nyuFileLocation + Path.GetFileName(item.invoiceno.Replace(@"/", "").ToString() + ".pdf");
                        if (System.IO.File.Exists(csvPath))
                        {
                            item.IsAttached = true;
                        }
                        else
                        {
                            item.IsAttached = false;
                        }
                    }
                    else
                    {
                        return null;
                    }
                }

                var Results = new
                {
                    Data = list,
                    page,
                    Total = Data.Count()
                };
                return Json(Results);
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        [HttpGet]
        public ActionResult GetArchieveInvoicesLoad(string serlpono = "", string serinvoiceno = "", string serinvfromdate = "", string serinvtodate = "", long serpaystatus = 0, int page = 1)
        {
            try
            {
                serlpono = serlpono ?? "";
                serinvoiceno = serinvoiceno ?? "";
                DateTime From = string.IsNullOrEmpty(serinvfromdate) ? DateTime.MinValue : DateTime.ParseExact(serinvfromdate, "dd/MM/yyyy", null);
                DateTime To = string.IsNullOrEmpty(serinvtodate) ? DateTime.MaxValue : DateTime.ParseExact(serinvtodate, "dd/MM/yyyy", null);
                int pageIndex = Convert.ToInt32(1) - 1;
                var Data = _INyuService.GetCustomerInvoicesLoad().OrderByDescending(x => x.createddate).Where(x =>
              (x.lpono.ToLower().Contains(serlpono.ToLower()) || serlpono == "")
               && (x.invoicedate >= From && x.invoicedate <= To)
              && (x.invoiceno.ToLower().Contains(serinvoiceno.ToLower()) || serinvoiceno == "")
               && (x.paystatus == serpaystatus || serpaystatus == 0)
            ).Select(x => new nyuinvoicemodal
            {
                id = x.id,
                lpono = x.lpono == null ? "" : x.lpono.ToString(),
                invoiceno = x.invoiceno == null ? "" : x.invoiceno.ToString(),
                invoicedate = x.invoicedate == null ? "" : x.invoicedate.Value.ToString("dd-MMM-yyyy"),
                verifiedby = x.verifieduser.fullname,
                verifiedon = x.verifiedon.Value.ToString("dd-MMM-yyyy"),
                paystatus = x.paystatus
            });

                var list = Data.Skip((page - 1) * 250).Take(250).ToList();

                foreach (var item in list)
                {

Portal/Portal/Views/Nyu/View_ArchievesInvoicesLoad.cshtml
@{
    Layout = "~/Views/Shared/_MainLayOut.cshtml";
}
<link href="~/css/Custom.css" rel="stylesheet" />

<header class="page-header">
    <h2>Invoices List</h2>
    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>Home</span></li>
            <li><span>Home</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open=""><i class="fa fa-chevron-left"></i></a>
    </div>
</header>
<div class="row">
    <div class="panel-body">
        <div class="col-md-12">
            <div class="right">
                <button type="button" class="mb-xs mt-xs mr-xs btn btn-default" id="btnreset"><i class="fa fa-refresh"></i> Refresh</button>
                <button type="button" class="mb-xs mt-xs mr-xs btn btn-primary" id="btnSearch"><i class="fa fa-search"></i> Search</button>
                <button type="button" class="mb-xs mt-xs mr-xs btn btn-primary" id="btnExport"><i class="fa fa-download"></i> Download</button>
            </div>
        </div>
    </div>
</div>
<hr class="separator" />
<div class="row">
    <div class="panel-body">
        <div class="col-md-12">
            <section class="panel">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label class="control-label">Lpo#</label>
                                <input type="text" id="serlpono" class="form-control">
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <label class="control-label">Invoice#</label>
                                <input type="text" id="serinvoiceno" class="form-control">
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="control-label">Inv From Date</label>
                                <input type="text" id="serinvfromdate" data-plugin-datepicker="" data-date-format="dd/mm/yyyy" class="form-control">
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="control-label">In To Date</label>
                                <input type="text" id="serinvtodate" data-plugin-datepicker="" data-date-format="dd/mm/yyyy" class="form-control">
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="control-label">Pay Status</label>
                                <select data-plugin-selectTwo class="form-control populate" id="serpaystatus">
                                    <option value="0">Select All</option>
                                    <option value="2">Paid</option>
                                    <option value="1">Not Paid</option>
                                    >
                                </select>
                            </div>
                        </div>
                    </div>

                </div>
            </section>
        </div>
    </div>
</div>
<hr class="separator" />
<div class="row">
    <div class="panel-body">
        <div class="col-md-12">
            <section class="panel">
                <div class="panel-body">
                    <div class="table-responsive">
                        <table id="list-InvoicesLoad" class="table table-bordered table-hover mb-none">
                        </table>
                        <div class="panel-body">
                            <div class="row datatables-footer" id="list-InvoicesLoad-pagination"></div>
                        </div>
                    </div>
                </div>
            </section>
        </div>

    </div>
</div>
<script src="~/lib/jquery/dist/jquery-3.5.1.min.js"></script>
<script src="~/assets/javascripts/theme.init.js"></script>
<script src="~/Scripts/Nyu/ArchievesInvoicesLoad.js"></script>

Portal/Portal/Views/Nyu/View_InvoiceDetails.cshtml
@model Portal.UI.Models.Nyu.nyuinvoicemodal
@{
    ViewData["Title"] = "View_VerifiedInvoiceDetails";
    Layout = "~/Views/Shared/_MainLayOut.cshtml";
}
<link href="~/css/Custom.css" rel="stylesheet" />
@if (ViewBag.Section != null)
{
    <input type="hidden" value="Success" id="SuccessData" />
}
else
{
    <input type="hidden" value="First" id="SuccessData" />
}
<div id="modalForm" class="modal-block modal-block-full mfp-hide">
    <section class="panel">
        <header class="panel-heading">
            <h2 class="panel-title">Invoice Details</h2>
        </header>
        <div class="panel-body">
            <form id="Details-form" class="form-horizontal mb-lg" novalidate="novalidate">
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-2">
                            <label class="control-label">Service Type</label>
                            <input type="text" name="servicetype" id="servicetype" class="form-control" required autocomplete="off" />
                            <input type="hidden" name="DetailsId" id="detailsId" class="form-control" required />
                        </div>
                        <div class="col-md-2">
                            <label class="control-label">Voucher#</label>
                            <input type="text" name="bookno" id="bookno" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-3">
                            <label class="control-label">Guest/Passenger</label>
                            <input type="text" name="pax" id="pax" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-1">
                            <label class="control-label">Service From</label>
                            <input type="text" id="fromdate" data-plugin-datepicker="" data-date-format="dd-M-yyyy" class="form-control" autocomplete="off">
                        </div>
                        <div class="col-md-1">
                            <label class="control-label">Service To</label>
                            <input type="text" id="todate" data-plugin-datepicker="" data-date-format="dd-M-yyyy" class="form-control" autocomplete="off">
                        </div>
                        <div class="col-md-3">
                            <label class="control-label">Service Provider</label>
                            <input type="text" name="provider" id="provider" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-3">
                            <label class="control-label">Route/City</label>
                            <input type="text" name="route" id="route" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-3">
                            <label class="control-label">Fare</label>
                            <input type="text" name="fare" id="fare" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-3">
                            <label class="control-label">Tax</label>
                            <input type="text" name="tax" id="tax" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-3">
                            <label class="control-label">Vat</label>
                            <input type="text" name="vat" id="vat" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-1">
                            <label class="control-label">Requester</label>
                            <input type="text" name="authcode" id="authcode" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-1">
                            <label class="control-label">Account</label>
                            <input type="text" name="account" id="account" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-1">
                            <label class="control-label">Fund</label>
                            <input type="text" name="fund" id="fund" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-1">
                            <label class="control-label">Org</label>
                            <input type="text" name="org" id="org" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-1">
                            <label class="control-label">Project</label>
                            <input type="text" name="project" id="project" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-1">
                            <label class="control-label">Program</label>
                            <input type="text" name="program" id="program" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-1">
                            <label class="control-label">Status</label><br />
                            <div class="switch switch-primary">
                                <input type="checkbox" name="status" id="status" data-plugin-ios-switch checked />
                            </div>
                        </div>
                        <input name="__RequestVerificationToken" type="hidden">
                    </div>
                </div>
            </form>
        </div>
        <footer class="panel-footer">
            <div class="row">
                <div class="col-md-12 text-right">
                    <button class="btn btn-primary modal-confirm" id="btnDetails">Update</button>
                    <button class="btn btn-default modal-dismiss">Close</button>
                </div>
            </div>
        </footer>
    </section>
</div>
<header class="page-header">
    <h2>Invoice Details</h2>
    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>Home</span></li>
            <li><span>Home</span></li>
        </ol>
        <a class="sidebar-right-toggle" data-open=""><i class="fa fa-chevron-left"></i></a>
    </div>
</header>

<div class="row">
    <div class="panel-body">
        <div class="col-md-12">
            <section class="panel">
                <div class="panel-body">
                    <div class="row">
                        <form role="form" asp-action="ApproveInvoice" asp-controller="Nyu" method="post" asp-antiforgery="true">
                           
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <label class="control-label">Lpo#</label>
                                    <input type="text" asp-for="lpono" class="form-control" disabled="disabled">
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <label class="control-label">Invoice#</label>
                                    <input type="text" asp-for="invoiceno" class="form-control" readonly="readonly">
                                    <input type="hidden" asp-for="id" class="form-control">
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <label class="control-label">Invoice Date</label>
                                    <input type="text" asp-for="invoicedate" class="form-control" readonly="readonly">
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <label class="control-label">Travel Code</label>
                                    <input type="text" asp-for="travelcode" class="form-control" readonly="readonly">
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <label class="control-label">Authorizer Code</label>
                                    <input type="text" asp-for="authcode" class="form-control" readonly="readonly">
                                </div>
                            </div>

                            <div class="col-sm-1">
                                <br />
                                <div>
                                    <button type="submit" class="mb-xs mt-xs mr-xs btn btn-primary" id="btnapprove">
                                        Approve
                                    </button>
                                    <input name="__RequestVerificationToken" type="hidden">
                                </div>
                            </div>
                            <div class="col-sm-1">
                                <br />
                                <div>
                                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-primary" id="btnadd">
                                        Add
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
<hr class="separator" />
<div class="row">
    <div class="panel-body">
        <div class="col-md-12">
            <section class="panel">
                <div class="panel-body">
                    <div class="table-responsive">
                        <table id="list-InvoiceDetails" class="table table-bordered table-hover mb-none">
                        </table>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
<script src="~/lib/jquery/dist/jquery-3.5.1.min.js"></script>
<script src="~/assets/javascripts/theme.init.js"></script>
<script src="~/Scripts/Nyu/InvoiceDetails.js"></script>