Portal/Portal/Models/Settings/UseregistrationModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Portal.UI.Models.Settings
{
    public class RegistrationModel
    {
        [Required]
      
        //[StringLength(15, ErrorMessage = "Name length can't be more than 15.")]
        public string Name { get; set; }
        [Required]
      
        public string Mobile { get; set; }
        [Required]
        
        public string Email { get; set; }

        [Required]
       
        public string Password { get; set; }
   
       
    }
}

Portal/Portal/Models/Settings/UsertypeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portal.UI.Models.Settings
{
    public class UsertypeModel
    {
        public string name { get; set; }
    }
}

Portal/Portal/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Portal.Data;
using Portal.UI.Models.Settings;

namespace Portal.UI.Controllers
{
    public class SettingsController : Controller
    {        
        private readonly ILogger<SettingsController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public SettingsController(ILogger<SettingsController> logger,  UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, RoleManager<IdentityRole> roleManager)
        {
            _logger = logger;           
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }       
        [HttpPost]
        [ValidateAntiForgeryToken]
        private async Task<IActionResult> CreateRole(UsertypeModel UsertypeModel)
        {
            bool x = await _roleManager.RoleExistsAsync(UsertypeModel.name);
            if (!x)
            {                  
                var role = new IdentityRole();
                role.Name = UsertypeModel.name;
                IdentityResult result= await _roleManager.CreateAsync(role);
               if(result.Succeeded)
                    return View(UsertypeModel);
            }
            return View(UsertypeModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateUser(RegistrationModel UseregistrationModel)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser appUser = new ApplicationUser
                {
                    UserName = UseregistrationModel.Name,
                    Email = UseregistrationModel.Email
                };

                IdentityResult result = await _userManager.CreateAsync(appUser, UseregistrationModel.Password);
                if (result.Succeeded)
                {                    
                    var rolresult= await _userManager.AddToRoleAsync(appUser, "Corporate");
                    if(rolresult.Succeeded)
                    return RedirectToAction("Index");
                }                  
                else
                {
                    foreach (IdentityError error in result.Errors)
                        ModelState.AddModelError("", error.Description);
                }
            }
            return View(UseregistrationModel);
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View("../Settings/View_RegisterNewUser");
        }
    }
}

Portal/Portal/Views/Settings/View_RegisterNewUser.cshtml
@{
    ViewData["Title"] = "View_Login";
}
@model Portal.UI.Models.Settings.RegistrationModel
<h2 class="text-center">Registar</h2>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="jumbotron">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <form role="form" asp-action="CreateUser" asp-controller="Settings" method="post" asp-antiforgery="true">

                <div class="form-group">
                    <label for="Name">User Name</label>
                    <input type="text" name="Name" asp-for="Name" class="form-control input-sm" autocomplete="off" data-val="true" data-val-required="The Mobile field is required." placeholder="Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Mobile"></label>
                    <input type="text" name="Mobile" data-val="true" autocomplete="off" data-val-required="The Mobile field is required." asp-for="Mobile" class="form-control input-sm" placeholder="Mobile">
                    <span asp-validation-for="Mobile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="Email">Email</label>
                    <input type="email" name="Email" asp-for="Email" autocomplete="off" data-val="true" class="form-control input-sm" data-val-required="The Mobile field is required." placeholder="Email Address">
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="Password">Password</label>
                    <input type="password" name="Password" asp-for="Password" autocomplete="off" class="form-control input-sm" data-val="true" data-val-required="The Mobile field is required." placeholder="Password">
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>                
                <input type="submit" value="Register" class="btn btn-info btn-block">
                <input name="__RequestVerificationToken" type="hidden" value="<removed for brevity>">
            </form>
        </div>
    </div>

</div>