Portal/Portal/Models/Corporate/corporatecompanymodal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portal.UI.Models.Corporate
{
    public class corporatecompanymodal
    {
        
            public Int64 id { get; set; }
            public string code { get; set; }
            public string name { get; set; }
            public string address { get; set; }
            public string secaddress { get; set; }

            public string thirdaddress { get; set; }

            public string forthaddress { get; set; }
            public string phone { get; set; }
            public string mail { get; set; }
            public string invformat { get; set; }
            public string currency { get; set; }
            public int status { get; set; }
            public string vat { get; set; }
            public string createdon { get; set; }

            public string createdby { get; set; }
        }
    
}

Portal/Portal/Models/Corporate/corporateinvoicedetailsexportmodal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portal.UI.Models.Corporate
{
    public class corporateinvoicedetailsexportmodal
    {
        public string companyname { get; set; }
        public string lpono { get; set; }
        public string lpodate { get; set; }
        public string invoiceno { get; set; }
        public string invoicedate { get; set; }
        public string servicetype { get; set; }
        public string bookno { get; set; }
        public string guest { get; set; }
        public string from { get; set; }
        public string to { get; set; }
        public string provider { get; set; }
        public string route { get; set; }
        public double fare { get; set; }
        public double tax { get; set; }
        public double vat { get; set; }
        public double sc { get; set; }

        public double total { get; set; }

        public string issuedate { get; set; }

        public string type { get; set; }
    }
}

Portal/Portal/Models/Corporate/corporateinvoicedetailsmodal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portal.UI.Models.Corporate
{
    public class corporateinvoicedetailsmodal
    {
       public long id { get; set; }
        public string servicetype { get; set; }
    
        public string bookno { get; set; }
        public string guest { get; set; }
        public string from { get; set; }
        public string to { get; set; }
        public string provider { get; set; }
        public string route { get; set; }
        public string fare { get; set; }
        public string tax { get; set; }
        public string vat { get; set; }
        public string sc { get; set; }
        public int status { get; set; }
        public string total { get; set; }
        public string issuedate { get; set; }
        public int billinginvoiceLine { get; set; }
        public long invoiceid { get; set; }

        public string type { get; set; }
    }
}

Portal/Portal/Models/Corporate/corporateinvoicemodal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portal.UI.Models.Corporate
{
    public class corporateinvoicemodal
    {
        public Int64 id { get; set; }
        public string companyname { get; set; }
        public string lpono { get; set; }
        public string lpodate { get; set; }
        public string invoiceno { get; set; }
        public string invoicedate { get; set; }
        public string verifiedby { get; set; }
        public string verifiedon { get; set; }
        public string attachment { get; set; }
        public int paystatus { get; set; }      
    }
}

Portal/Portal/Models/Corporate/corporatesoamodal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Portal.UI.Models.Corporate
{
    public class corporatesoamodal
    {
        public Int64 id { get; set; }
        public string companyname { get; set; }
        public string lpono { get; set; }
        public string lpodate { get; set; }
        public string invoiceno { get; set; }
        public string invoicedate { get; set; }
        public string debit { get; set; }
        public string credit { get; set; }
        public string balance { get; set; }
        public Int64 invoiceid { get; set; }
        public string companycode { get; set; }
    }
}

Portal/Portal/Controllers/CorporateController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Scaffolding.Metadata;
using Portal.Data;
using Portal.Data.Corporate;
using Portal.Service.Interface;
using Portal.UI.Models.Corporate;

namespace Portal.UI.Controllers
{
    [Authorize(Roles = "CorporateNtt")]
    public class CorporateController : Controller
    {
        public ICorporateService _ICorporateService;
        public IAttachmentService _IAttachmentService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        public static string CorporateFileLocation = @"D:\Attachments\";
        public static string infordocslocation = @"D:\InforDocs\";
        public CorporateController(ICorporateService corporateService, IAttachmentService attachmentService, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _ICorporateService = corporateService;
            _IAttachmentService = attachmentService;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public IActionResult CorporateLoad()
        {
            return View("../Corporate/View_CorporateLoad");
        }
        public IActionResult StaffveriLoad()
        {
            return View("../Corporate/View_StaffveriLoad");
        }
        public IActionResult InvoicesLoad()
        {
            return View("../Corporate/View_InvoicesLoad");
        }
        public IActionResult SoaLoad()
        {
            return View("../Corporate/View_SoaLoad");
        }       
        [HttpGet]
        public ActionResult GetCorporateLoad(string sercode = "", string sername = "", string serregno = "", string serinvformat="", string sercurrencyId = "", int page = 1)
        {
            try
            {
                sercode = sercode ?? "";
                sername = sername ?? "";
                serregno = serregno ?? "";
                serinvformat = serinvformat ?? "";
                sercurrencyId = sercurrencyId ?? "";               
                int pageIndex = Convert.ToInt32(1) - 1;
                var Data = _ICorporateService.GetCorporateLoad().OrderByDescending(x => x.createddate).Where(x =>
              (x.code.ToLower().Contains(sercode.ToLower()) || sercode == "")
              && (x.name.ToLower().Contains(sername.ToLower()) || sername == "")
              && (x.invformat.ToLower().Contains(serinvformat.ToLower()) || serinvformat == "")
              && (x.regno.ToLower().Contains(serregno.ToLower()) || serregno == "")
              && (x.currency.ToLower().Contains(sercurrencyId.ToLower()) || sercurrencyId == "")
            ).OrderByDescending(x=>x.createddate).Select(x => new corporatecompanymodal
            {
                id = x.id,
                code = x.code==null?"": x.code.ToString(),
                name =x.name==null?"": x.name.ToString(),
                address = x.firstaddress==null?"": x.firstaddress.ToString(),
                secaddress=x.secondaddress==null?"":x.secondaddress.ToString(),
                thirdaddress=x.thirdaddress==null?"": x.thirdaddress.ToString(),
                forthaddress=x.forthaddress==null ? "" : x.forthaddress.ToString(),
                currency=x.currency==null?"": x.currency.ToString(),
                phone = x.phone==null?"": x.phone.ToString(),
                mail = x.mail==null?"": x.mail.ToString(),
                vat= x.regno==null?"": x.regno.ToString(),
                invformat = x.invformat==null?"": x.invformat.ToString(),              
                status = x.status              
            }); ;
                var Results = new
                {
                    Data = Data.Skip((page - 1) * 150).Take(150).ToList(),
                    page,
                    Total = Data.Count()
                };
                return Json(Results);
            }
            catch (Exception ex)
            {

                throw;
            }
        }
        [HttpGet]
        public ActionResult GetStaffveriLoad(long sercustomer = 0, string serlpono = "", string serinvoiceno = "", string serinvfromdate = "", string serinvtodate = "", int page = 1)
        {
            try
            {
                serlpono = serlpono ?? "";
                serinvoiceno = serinvoiceno ?? "";
                DateTime From = string.IsNullOrEmpty(serinvfromdate) ? DateTime.MinValue : DateTime.ParseExact(serinvfromdate, "dd/MM/yyyy", null);
                DateTime To = string.IsNullOrEmpty(serinvtodate) ? DateTime.MaxValue : DateTime.ParseExact(serinvtodate, "dd/MM/yyyy", null);
                int pageIndex = Convert.ToInt32(1) - 1;
                var Data = _ICorporateService.GetStaffverificationload().OrderByDescending(x => x.createddate).Where(x =>
              (x.lpono.ToLower().Contains(serlpono.ToLower()) || serlpono == "")
                && (x.invoicedate >= From && x.invoicedate <= To)
              && (x.invoiceno.ToLower().Contains(serinvoiceno.ToLower()) || serinvoiceno == "")
               && (x.companyid == sercustomer || sercustomer == 0) && x.corporatecompany.status>0
            ).Select(x => new corporateinvoicemodal
            {
                id = x.id,
                companyname = x.corporatecompany.name.ToString(),
                lpono = x.lpono==null ? "":x.lpono.ToString(),
                lpodate = x.lpodate==null? "": x.lpodate.Value.ToString("dd-MMM-yyyy"),
                invoiceno = x.invoiceno==null? "": x.invoiceno.ToString(),
                invoicedate = x.invoicedate==null? "":x.invoicedate.Value.ToString("dd-MMM-yyyy"),
            }); ;
                var Results = new
                {
                    Data = Data.Skip((page - 1) * 250).Take(250).ToList(),
                    page,
                    Total = Data.Count()
                };
                return Json(Results);
            }
            catch (Exception ex)
            {

                throw;
            }
        }
        [HttpGet]
        public ActionResult GetInvoicesLoad(long sercustomer = 0, string serlpono = "", string serinvoiceno = "", string serinvfromdate = "", string serinvtodate = "", long serpaystatus = 0, int page = 1)
        {
            try
            {
                serlpono = serlpono ?? "";
                serinvoiceno = serinvoiceno ?? "";
                DateTime From = string.IsNullOrEmpty(serinvfromdate) ? DateTime.MinValue : DateTime.ParseExact(serinvfromdate, "dd/MM/yyyy", null);
                DateTime To = string.IsNullOrEmpty(serinvtodate) ? DateTime.MaxValue : DateTime.ParseExact(serinvtodate, "dd/MM/yyyy", null);
                int pageIndex = Convert.ToInt32(1) - 1;
                var Data = _ICorporateService.GetCustomerInvoicesLoad().OrderByDescending(x => x.createddate).Where(x =>
              (x.lpono.ToLower().Contains(serlpono.ToLower()) || serlpono == "")
              && (x.invoiceno.ToLower().Contains(serinvoiceno.ToLower()) || serinvoiceno == "")
                && (x.invoicedate >= From && x.invoicedate <= To)
              && (x.companyid == sercustomer || sercustomer == 0)
               && (x.paystatus == serpaystatus || serpaystatus == 0) && x.status>1
            ).Select(x => new corporateinvoicemodal
            {

                id = x.id,
                companyname = x.corporatecompany.name.ToString(),
                lpono = x.lpono==null?"" : x.lpono.ToString(),
                lpodate = x.lpodate==null?"": x.lpodate.Value.ToString("dd-MMM-yyyy"),
                invoiceno = x.invoiceno==null?"":x.invoiceno.ToString(),
                invoicedate = x.invoicedate==null?"": x.invoicedate.Value.ToString("dd-MMM-yyyy"),
                verifiedby = x.verifieduser.fullname.ToString(),
                verifiedon = x.verifiedon.Value.ToString("dd-MMM-yyyy"),
                paystatus = x.paystatus
            });
                var Results = new
                {
                    Data = Data.Skip((page - 1) * 250).Take(250).ToList(),
                    page,
                    Total = Data.Count()
                };
                return Json(Results);
            }
            catch (Exception ex)
            {

                throw;
            }
        }
        [HttpGet]
        public ActionResult GetSoaLoad(long sercustomer = 0, string serlpono = "", string serinvoiceno = "", string serinvfromdate = "", string serinvtodate = "", string companycode= "", int page = 1)
        {
            try
            {
                serlpono = serlpono ?? "";
                serinvoiceno = serinvoiceno ?? "";
                companycode = companycode ?? "";
                DateTime From = string.IsNullOrEmpty(serinvfromdate) ? DateTime.MinValue : DateTime.ParseExact(serinvfromdate, "dd/MM/yyyy", null);
                DateTime To = string.IsNullOrEmpty(serinvtodate) ? DateTime.MaxValue : DateTime.ParseExact(serinvtodate, "dd/MM/yyyy", null);
                int pageIndex = Convert.ToInt32(1) - 1;
                var Data = _ICorporateService.GetSOALoad().OrderByDescending(x => x.createddate).Where(x =>
              (x.corporateinvoice.lpono.ToLower().Contains(serlpono.ToLower()) || serlpono == "")
              && (x.corporateinvoice.invoiceno.ToLower().Contains(serinvoiceno.ToLower()) || serinvoiceno == "")
                  && (x.corporateinvoice.invoicedate >= From && x.corporateinvoice.invoicedate <= To)
               && (x.corporateinvoice.corporatecompany.id == sercustomer || sercustomer == 0)
                && (x.corporateinvoice.corporatecompany.code.ToLower().Contains(companycode.ToLower()) || companycode == "")
            ).Select(x => new corporatesoamodal
            {
                id = x.id,

Portal/Portal/Views/Corporate/View_InvoiceDetails.cshtml
@model Portal.UI.Models.Corporate.corporateinvoicemodal
@{
    ViewData["Title"] = "View_VerifiedInvoiceDetails";
    Layout = "~/Views/Shared/_MainLayOut.cshtml";
}
<link href="~/css/Custom.css" rel="stylesheet" />
@if (ViewBag.Section != null)
{
    <input type="hidden" value="Success" id="SuccessData" />
}
else
{
    <input type="hidden" value="First" id="SuccessData" />
}
<div id="modalForm" class="modal-block modal-block-full mfp-hide">
    <section class="panel">
        <header class="panel-heading">
            <h2 class="panel-title">Invoice Details</h2>
        </header>
        <div class="panel-body">
            <form id="Details-form" class="form-horizontal mb-lg" novalidate="novalidate">
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-2">
                            <label class="control-label">Service Type</label>
                            <input type="text" name="servicetype" id="servicetype" class="form-control" required autocomplete="off" />
                            <input type="hidden" name="DetailsId" id="detailsId" class="form-control" required />
                        </div>
                        <div class="col-md-2">
                            <label class="control-label">Line#</label>
                            <input type="text" name="billinginvoiceLine" id="billinginvoiceLine" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-2">
                            <label class="control-label">Voucher#</label>
                            <input type="text" name="bookno" id="bookno" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-3">
                            <label class="control-label">Guest/Passenger</label>
                            <input type="text" name="guest" id="guest" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-1">
                            <label class="control-label">Service From</label>
                            <input type="text" id="from" data-plugin-datepicker="" data-date-format="dd-M-yyyy" class="form-control" autocomplete="off">
                        </div>
                        <div class="col-md-1">
                            <label class="control-label">Service To</label>
                            <input type="text" id="to" data-plugin-datepicker="" data-date-format="dd-M-yyyy" class="form-control" autocomplete="off">
                        </div>
                        <div class="col-md-1">
                            <label class="control-label">Issue Date</label>
                            <input type="text" id="issuedate" data-plugin-datepicker="" data-date-format="dd-M-yyyy" class="form-control" autocomplete="off">
                        </div>
                        <div class="col-md-3">
                            <label class="control-label">Service Provider</label>
                            <input type="text" name="provider" id="provider" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-3">
                            <label class="control-label">Sector/City</label>
                            <input type="text" name="route" id="route" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-2">
                            <label class="control-label">Fare</label>
                            <input type="text" name="fare" id="fare" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-2">
                            <label class="control-label">Tax</label>
                            <input type="text" name="tax" id="tax" class="form-control" required autocomplete="off" />
                        </div>

                        <div class="col-md-1">
                            <label class="control-label">Vat</label>
                            <input type="text" name="vat" id="vat" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-1">
                            <label class="control-label">SC</label>
                            <input type="text" name="sc" id="sc" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-3">
                            <label class="control-label">Class Type / Room Type</label>
                            <input type="text" name="type" id="type" class="form-control" required autocomplete="off" />
                        </div>
                        <div class="col-md-2">
                            <label class="control-label">Status</label><br />
                            <div class="switch switch-primary">
                                <input type="checkbox" name="status" id="status" data-plugin-ios-switch checked />
                            </div>
                        </div>
                        <input name="__RequestVerificationToken" type="hidden">
                    </div>
                </div>
            </form>
        </div>
        <footer class="panel-footer">
            <div class="row">
                <div class="col-md-12 text-right">
                    <button class="btn btn-primary modal-confirm" id="btnDetails">Update</button>
                    <button class="btn btn-default modal-dismiss">Close</button>
                </div>
            </div>
        </footer>
    </section>
</div>

<div id="modalrm" class="modal-block modal-block-sm mfp-hide">
    <section class="panel">
        <header class="panel-heading">
            <h2 class="panel-title">Remarks</h2>
        </header>
        <div class="panel-body">
            <div class="col-md-2">
                <div class="form-group" id="divRmDetails">
                    <label class="control-label">Rmvalue</label>
                    <input type="text" id="txtRMvalue" class="form-control">
                    <input type="hidden" id="hdnRmId" />
                </div>
                <button type="button" class="mb-xs mt-xs mr-xs btn btn-primary" id="btnsaveRm">
                    Save
                </button>
            </div>
                <div class="table-responsive">
                    <table id="list-RmDetails" class="table table-bordered table-hover mb-none">
                    </table>
                </div>
            </div>
            <footer class="panel-footer">
                <div class="row">
                    <div class="col-md-12 text-right">
                        <button class="btn btn-default modal-dismiss">Close</button>
                    </div>
                </div>
            </footer>
</section>
</div>
<header class="page-header">
    <h2>Invoice Details</h2>
    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>Home</span></li>
            <li><span>Home</span></li>
        </ol>
        <a class="sidebar-right-toggle" data-open=""><i class="fa fa-chevron-left"></i></a>
    </div>
</header>
<div class="row">
    <div class="panel-body">
        <div class="col-md-12">
            <section class="panel">
                <div class="panel-body">
                    <div class="row">
                        <form role="form" asp-action="ApproveInvoice" asp-controller="Corporate" method="post" asp-antiforgery="true">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            @Html.AntiForgeryToken()
                        <div class="col-sm-2">
                            <div class="form-group">
                                <label class="control-label">Lpo#</label>
                                <input type="text" asp-for="lpono" class="form-control" readonly="readonly">
                            </div>
                        </div>
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <label class="control-label">Lpo Date</label>
                                    <input type="text" asp-for="lpodate" class="form-control" readonly="readonly">
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <label class="control-label">Invoice#</label>
                                    <input type="text" asp-for="invoiceno" class="form-control" readonly="readonly">
                                    <input type="hidden" asp-for="id" class="form-control">
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <label class="control-label">Invoice Date</label>
                                    <input type="text" asp-for="invoicedate" class="form-control" readonly="readonly">
                                </div>
                            </div>

                            @*<div class="col-sm-2">
                                <div class="form-group">
                                    <label class="control-label">Total Fare</label>
                                    <input type="text" asp-for="lpono" class="form-control" readonly="readonly">
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <label class="control-label">Total Tax</label>
                                    <input type="text" asp-for="lpono" class="form-control" readonly="readonly">
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <label class="control-label">Total Service Fee</label>
                                    <input type="text" asp-for="lpono" class="form-control" readonly="readonly">
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <div class="form-group">
                                    <label class="control-label">Invoice Total</label>
                                    <input type="text" asp-for="lpono" class="form-control" readonly="readonly">
                                </div>
                            </div>*@
                            <div class="col-sm-1">
                                <br />
                                <div>
                                    @*<button type="button" class="mb-xs mt-xs mr-xs btn btn-primary"><i class="fa fa-check"></i> Approve</button>*@
                                    <button type="submit" class="mb-xs mt-xs mr-xs btn btn-primary" id="btnapprove">
                                        Approve
                                    </button>
                                    <input name="__RequestVerificationToken" type="hidden">
                                </div>
                            </div>
                            <div class="col-sm-1">
                                <br />
                                <div>
                                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-primary" id="btnadd" style="width: 80px;">
                                        Add
                                    </button>
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <br />
                                <div>
                                    <button type="button" class="mb-xs mt-xs mr-xs btn btn-primary" id="btrm">
                                        <i class="fa fa-bookmark"></i>  Remarks
                                    </button>
                                </div>
                            </div>
                        </form>

                    </div>
            </section>
        </div>
    </div>
</div>
<hr class="separator" />
<div class="row">
    <div class="panel-body">
        <div class="col-md-12">
            <section class="panel">
                <div class="panel-body">
                    <div class="table-responsive">
                        <table id="list-InvoiceDetails" class="table table-bordered table-hover mb-none">
                        </table>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
<script src="~/lib/jquery/dist/jquery-3.5.1.min.js"></script>
<script src="~/assets/javascripts/theme.init.js"></script>
<script src="~/Scripts/Corporate/InvoiceDetails.js"></script>